# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=0)),
                ('agency', models.CharField(max_length=200)),
                ('salary_range_from', models.IntegerField(default=0)),
                ('salary_range_to', models.IntegerField(default=0)),
                ('posting_date', models.DateTimeField(verbose_name='date posted')),
                ('post_until', models.DateTimeField(verbose_name='final date')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
