# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 04:12
from __future__ import unicode_literals
from django.db import migrations, models

def load_jobs(apps, schema_editor):
  Jobs = apps.get_model("workmarket", "Jobs")
  # with open("workmarket/NYC_Jobs.csv", "r") as myfile:
  #   for line in myfile:
  #     split_line = line.split(',')
  #     split_line = map(strip, split_line)
  #     new_job = Jobs(job_id=split_line[0], 
  #                   agency=split_line[1], 
  #                   salary=split_line[2],
  #                   posting_date=split_line[3],
  #                   post_updated=split_line[4])
  #     new_job.save()
      

class Migration(migrations.Migration):

    dependencies = [
        ('workmarket', '0002_auto_20170111_0349'),
    ]

    operations = [
      migrations.RunPython(load_jobs),
    ]
