# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmarket', '0004_jobs_salary_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='post_until',
            field=models.DateField(verbose_name='final date'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='posting_date',
            field=models.DateField(verbose_name='date posted'),
        ),
    ]
