# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workmarket', '0007_auto_20170111_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='post_until',
            new_name='post_updated',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='salary_range_from',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='salary_frequency',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='salary_range_to',
        ),
    ]
